### ISSUE TITLE
How did you create hams.16c?

### ISSUE THREAD

**Issue by dmp359** [electroduck/display16#2]
I would love to help write a program to go from mp4 > bitmap, but I'm having trouble doing it manually. Can you walk through how you did this?

**Comment by electroduck** [comment]
I've uploaded a video here: https://youtu.be/7WsfXkTw8dU
It isn't a _great_ tutorial, but it shows the process. Right now there is quite a bit of manual hex editing needed. (The numbers are entered 'backwards' in the hex editor because of how the x86 processor stores numbers.)

**Comment by dmp359** [comment]
Awesome. I'll check it out

**Comment by electroduck** [comment]
Did that help? Were you able to convert a video OK?

**Comment by dmp359** [comment]
I only had time to watch the video. The tutorial made sense! Once I get some free time i'll play around with it.
